- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create launch configuration
      ec2_lc:
        name: auto_launch_config
        image_id: ami-8c122be9
        key_name: my_keypair
        security_groups: ['sg-077235be171560627']
        instance_type: t2.micro
        volumes:
        - device_name: /dev/xvda
          volume_size: 100
          volume_type: gp2
          delete_on_termination: true
