#- name: populate service facts
#  service_facts:
#
#- debug:
#    var: ansible_facts.services

#- name: Install nginx
#  shell: "amazon-linux-extras install nginx1.12"
#  become: yes
#
#- name: Enable and start nginx
#  shell: "systemctl enable nginx && sudo systemctl start nginx"
#  become: yes

- name: Create env variable
  get_url:
    url: "http://169.254.169.254/latest/meta-data/instance-id"
    dest: "./"
#  register: instance_id

- name: Enable and start nginx
  shell: 'AWS_INSTANCEID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id); sed -i.bak "s|Website Administrator|${AWS_INSTANCEID}|g" /usr/share/nginx/html/index.html'
  become: yes 
  register: cattus

- debug: msg={{ cattus }}

#- name: Alter default index.html
#  shell: 'sed -i.bak "s|Website Administrator|${AWS_INSTANCEID}|g" /usr/share/nginx/html/index.html'
#  become: yes

#- name: Get region things
#  aws_az_facts:
#    aws_access_key:     "{{ aws_access_key }}"
#    aws_secret_key:     "{{ aws_secret_key }}"
#    region:             "us-east-1" #"{{ aws_region }}" 
#    filters:
#      zone-name: "us-west-2" 
#  register: region_info

#- name: Echo a list
#  debug:
#    msg: "An item: {{ item }}"
#  with_items: "{{ some_list }}"

#- name: Set fact and see if role-2 can read it
#  set_fact:
#    role_1_var:  "{{ region_info }}"

#  loop: "{{ some_list }}"
#- debug: msg={{ region_info }}
#- debug: msg={{ region_info|count }}
# - debug: msg={{ vpc_subnets }}
#
#
# "{{ aws_region }}" 
