- hosts: localhost
  connection: local
  #gather_facts: False

  tasks:
    - name: Get VPC details
      ec2_vpc_net_facts:
        aws_access_key: {{ aws_access_key }}
        aws_secret_key: {{ aws_secret_key }}
        filters:
          "tag:Name": default
      register: vpc_test

    - name: Get VPC subnet facts
      ec2_vpc_subnet_facts:
        aws_access_key: {{ aws_access_key }}
        aws_secret_key: {{ aws_secret_key }}
      register: vpc_subnets


    - debug: msg={{ vpc_test }}
    - debug: msg={{ vpc_subnets }}
