#- name: Get region things
#  aws_az_facts:
#    aws_access_key:     "{{ aws_access_key }}"
#    aws_secret_key:     "{{ aws_secret_key }}"
#    region:             "us-east-1" #"{{ aws_region }}" 
#    filters:
#      zone-name: "us-west-2" 
#  register: region_info

- name: Echo a list
  debug:
    msg: "{{ item }}"
  with_items: "{{ some_list }}"
#  loop: "{{ some_list }}"
#- debug: msg={{ region_info }}
#- debug: msg={{ region_info|count }}
# - debug: msg={{ vpc_subnets }}
#
#
# "{{ aws_region }}" 
