# Auto Scaling Group
asg_name:               "asg_1"
avail_zones:            [ "{{ aws_region }}a","{{ aws_region }}b" ]
asg_min:                "2"
asg_max:                "2"
asg_desired:            "2"
#asg_zone_ident:        Set as fact in roles/aws-prereqs/tasks/main.yml {{ subnet_a_id / subnet_b_id }} 

# Application Load Balancer 
elb_name:               "app-lb1"
#elb_secgrp_name:       Set as fact in roles/aws-prereqs/tasks/main.yml 
#websvr_secgrp_name     Set as fact in roles/aws-prereqs/tasks/main.yml 

